/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package game.view.panels;

import game.CardCollection.AbstractPile;
import game.CardCollection.DrawPile;
import game.CardCollection.NotSupportedOperationException;
import game.Cards.EmptyCard;
import game.Player.Player;
import game.master.GameMaster;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;


// TODO: Auto-generated Javadoc
/**
 * This class represents the Central Panel of the view with the cards
 * It Contains a HotizantalViewPanel for the Draw and the Discard Piles.
 *
 * @author Author
 */
public class CenterPanel extends javax.swing.JPanel {

    /** Creates new form CenterPanel. */
    private GameMaster game;
    
    /** The panel. */
    private HorizontalViewCardPanel panel;
    
    /** The players count. */
    private int playersCount = 0;
    
    /** The p. */
    private Player p;
    
    /** The f. */
    private PlayersPanel f;
    
    /**
     * Instantiates a new center panel.
     *
     * @param _game the _game
     * @param theFrame the the frame
     */
    public CenterPanel(GameMaster _game , PlayersPanel theFrame) {
        initComponents();
        this.game = _game;
        f = theFrame;
        p = this.game.getFirstPlayer();
        panel = new HorizontalViewCardPanel(p, false);
        
        panel.setMaximumSize(new Dimension(400, 140));
        panel.setPreferredSize(new Dimension(400, 140));
        panel.setOrigin(new Point(100,0));
        panel.changeCurrentPlayerColor();
        this.jPanel1.setOpaque(false);
        this.jPanel1.setVisible(true);
        this.jPanel1.setLayout(new BorderLayout());
        this.jPanel1.add(panel,BorderLayout.CENTER);
        
        EmptyCard tmp = new EmptyCard();
        //ViewCard card = new ViewCard(tmp,new Point(10,10),false ? Direction.UP : Direction.DOWN,tmp.getImagePath());
        //this.add(card);
        AbstractPile tmp1 = new DrawPile();
        try {
            tmp1.addCard(tmp);
        } catch (NotSupportedOperationException ex) {
            Logger.getLogger(CenterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setCards(tmp1);
    }

    
    /**
     * Clear all.
     */
    public void clearAll(){

    }
    
    /* (non-Javadoc)
     * @see javax.swing.JComponent#paintComponent(java.awt.Graphics)
     */
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        ImageIcon back = new ImageIcon(getClass().getResource("/game/images/background.jpg"));
        g.drawImage(back.getImage(), 0, 0, this.getWidth(), this.getHeight(), this);
    }
    

    /**
     * Change the player.
     */
    private void changeThePlayer(){
       
        this.jPanel1.removeAll();
        
        this.jPanel1.revalidate();
        this.jPanel1.repaint();
        
    }
    
    /**
     * Sets the cards.
     *
     * @param comb the new cards
     */
    public void setCards(AbstractPile comb){
        System.out.println("set CARDS Center panel -> ");
        this.panel.setCards(comb);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /** The j panel1. */
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
